/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountsProfiles {
    created_at: Generated<Timestamp>;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string | null;
    surname: string | null;
    user_id: string;
}

export interface AuthEmailVerificationTokens {
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
    id: string;
    token_hash: string;
    user_id: string;
}

export interface AuthPasswordResetTokens {
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
    id: string;
    token_hash: string;
    user_id: string;
}

export interface AuthRoles {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
}

export interface AuthRoleScopes {
    role_id: string;
    scope_id: string;
}

export interface AuthScopes {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    scope: string;
}

export interface AuthUserRoles {
    role_id: string;
    user_id: string;
}

export interface AuthUsers {
    active: Generated<number | null>;
    created_at: Generated<Timestamp>;
    email: string;
    id: string;
    modified_at: Generated<Timestamp>;
    password: string;
    public_id: string;
    verified: Generated<number | null>;
}

export interface WorkspacesTasks {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
    team_id: string;
}

export interface WorkspacesTeamInvitations {
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
    id: string;
    invitation_token: string;
    invited_email: string;
    modified_at: Generated<Timestamp>;
    status: Generated<string>;
    team_id: string;
}

export interface WorkspacesTeamMembers {
    created_at: Generated<Timestamp>;
    modified_at: Generated<Timestamp>;
    role_id: string;
    team_id: string;
    user_id: string;
}

export interface WorkspacesTeamRoles {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
}

export interface WorkspacesTeams {
    created_at: Generated<Timestamp>;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
    owner_id: string;
    public_id: string;
}

export interface WorkspacesTimesheets {
    created_at: Generated<Timestamp>;
    date: string;
    employee_id: string;
    end_hour: string;
    hours_worked: Generated<string | null>;
    id: string;
    modified_at: Generated<Timestamp>;
    start_hour: string;
    status: Generated<string | null>;
    task_id: string;
}

export interface DB {
    "accounts.profiles": AccountsProfiles;
    "auth.email_verification_tokens": AuthEmailVerificationTokens;
    "auth.password_reset_tokens": AuthPasswordResetTokens;
    "auth.role_scopes": AuthRoleScopes;
    "auth.roles": AuthRoles;
    "auth.scopes": AuthScopes;
    "auth.user_roles": AuthUserRoles;
    "auth.users": AuthUsers;
    "workspaces.tasks": WorkspacesTasks;
    "workspaces.team_invitations": WorkspacesTeamInvitations;
    "workspaces.team_members": WorkspacesTeamMembers;
    "workspaces.team_roles": WorkspacesTeamRoles;
    "workspaces.teams": WorkspacesTeams;
    "workspaces.timesheets": WorkspacesTimesheets;
}
