/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountsProfiles {
    created_at: Generated<Timestamp>;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string | null;
    surname: string | null;
    user_id: string;
}

export interface AuthEmailVerificationTokens {
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
    id: string;
    token_hash: string;
    user_id: string;
}

export interface AuthEmailVerificationTokensView {
    created_at: Timestamp | null;
    expires_at: Timestamp | null;
    id: string | null;
    token_hash: string | null;
    user_id: string | null;
}

export interface AuthPasswordResetTokens {
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
    id: string;
    token_hash: string;
    user_id: string;
}

export interface AuthPasswordResetTokensView {
    created_at: Timestamp | null;
    expires_at: Timestamp | null;
    id: string | null;
    token_hash: string | null;
    user_id: string | null;
}

export interface AuthRoles {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
}

export interface AuthRoleScopes {
    role_id: string;
    scope_id: string;
}

export interface AuthRoleScopesView {
    role_id: string | null;
    scope_id: string | null;
}

export interface AuthRolesView {
    created_at: Timestamp | null;
    description: string | null;
    id: string | null;
    modified_at: Timestamp | null;
    name: string | null;
}

export interface AuthScopes {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    scope: string;
}

export interface AuthScopesView {
    created_at: Timestamp | null;
    description: string | null;
    id: string | null;
    modified_at: Timestamp | null;
    scope: string | null;
}

export interface AuthUserRoles {
    role_id: string;
    user_id: string;
}

export interface AuthUserRolesView {
    role_id: string | null;
    user_id: string | null;
}

export interface AuthUsers {
    active: Generated<boolean | null>;
    created_at: Generated<Timestamp>;
    email: string;
    id: string;
    modified_at: Generated<Timestamp>;
    password: string;
    public_id: string;
    verified: Generated<boolean | null>;
}

export interface AuthUsersView {
    active: boolean | null;
    created_at: Timestamp | null;
    email: string | null;
    id: string | null;
    modified_at: Timestamp | null;
    password: string | null;
    public_id: string | null;
    verified: boolean | null;
}

export interface WorkspacesInvitationStatuses {
    id: number;
    name: string;
}

export interface WorkspacesTasks {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
    team_id: string;
}

export interface WorkspacesTeamInvitations {
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
    id: string;
    invitation_token: string;
    invited_email: string;
    modified_at: Generated<Timestamp>;
    status_id: Generated<number>;
    team_id: string;
}

export interface WorkspacesTeamMembers {
    created_at: Generated<Timestamp>;
    modified_at: Generated<Timestamp>;
    role_id: string;
    team_id: string;
    user_id: string;
}

export interface WorkspacesTeamRoles {
    created_at: Generated<Timestamp>;
    description: string | null;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
}

export interface WorkspacesTeams {
    created_at: Generated<Timestamp>;
    id: string;
    modified_at: Generated<Timestamp>;
    name: string;
    owner_id: string;
    public_id: string;
}

export interface WorkspacesTimesheets {
    created_at: Generated<Timestamp>;
    end_time: Timestamp;
    hours_worked: Generated<string | null>;
    id: string;
    modified_at: Generated<Timestamp>;
    start_time: Timestamp;
    status_id: Generated<number>;
    task_id: string;
    user_id: string;
}

export interface WorkspacesTimesheetStatuses {
    id: number;
    name: string;
}

export interface DB {
    "accounts.profiles": AccountsProfiles;
    "auth.email_verification_tokens": AuthEmailVerificationTokens;
    "auth.email_verification_tokens_view": AuthEmailVerificationTokensView;
    "auth.password_reset_tokens": AuthPasswordResetTokens;
    "auth.password_reset_tokens_view": AuthPasswordResetTokensView;
    "auth.role_scopes": AuthRoleScopes;
    "auth.role_scopes_view": AuthRoleScopesView;
    "auth.roles": AuthRoles;
    "auth.roles_view": AuthRolesView;
    "auth.scopes": AuthScopes;
    "auth.scopes_view": AuthScopesView;
    "auth.user_roles": AuthUserRoles;
    "auth.user_roles_view": AuthUserRolesView;
    "auth.users": AuthUsers;
    "auth.users_view": AuthUsersView;
    "workspaces.invitation_statuses": WorkspacesInvitationStatuses;
    "workspaces.tasks": WorkspacesTasks;
    "workspaces.team_invitations": WorkspacesTeamInvitations;
    "workspaces.team_members": WorkspacesTeamMembers;
    "workspaces.team_roles": WorkspacesTeamRoles;
    "workspaces.teams": WorkspacesTeams;
    "workspaces.timesheet_statuses": WorkspacesTimesheetStatuses;
    "workspaces.timesheets": WorkspacesTimesheets;
}
